### ISSUE TITLE
Docker Layer Caching issue on CircleCI

### ISSUE THREAD

**Issue by dannyrb** [OHIF/Viewers#1019]
URL: https://circleci.com/gh/OHIF/Viewers/4381#tests/containers/0

![image](https://user-images.githubusercontent.com/5797588/66510630-66fdf900-eaa3-11e9-964d-aef1b83c9726.png)

This is a new issue. It's causing all builds to fail. @igoroctaviano is commenting out docker layer caching in the short-term. I've submitted a ticket to CircleCI asking why we're seeing this error.

**Comment by dannyrb** [comment]
> Hello Danny,
> 
> Thank you for reaching out to CircleCI Support!
> 
> This message is due to the config node docker_layer_caching: true in the config.yml. Docker layer caching is only available to users on the performance plan.
> 
> If you'd like, I can put you in touch with an account representative who can discuss upgrading to a performance plan to take advantage of this feature.
> 
> Please let us know if you have any more questions, happy building!
> 
> Scott Wheeler
> Support Engineer @ CircleCI

Sending a response to indicate we've had these flags set for ~4/5 months

**Comment by dannyrb** [comment]
This impacts docker publish: https://circleci.com/gh/OHIF/Viewers/4413

**Comment by dannyrb** [comment]
This may be a part of a pricing restructure. We may no longer have access to this feature. If we don't hear back from support soon, we'll need to identify an alternative way to docker publish:

https://circleci.com/pricing/usage/

**Comment by dannyrb** [comment]
Docker Orb: https://circleci.com/orbs/registry/orb/circleci/docker
GitHub: https://github.com/CircleCI-Public/docker-orb

May use `docker_layer_caching` under the hood.

```
orbs:
  docker: circleci/docker@x.y.z
version: 2.1
workflows:
  build-and-publish-docker-image:
    jobs:
      - docker/publish:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
```
