### ISSUE TITLE
How can I turn off CORS and go directly from the OHIF container to a dicom-web destination in Docker ohif/viewer?

### ISSUE THREAD

**Issue by cutecycle** [OHIF/Viewers#1315]
**Description**

I have an older meteor-based configuration of the OHIF viewer that made requests to an Orthanc dicom-web endpoint over the loopback interface. 

I'm trying to recreate this in docker-compose, but I'm seeing errors in-console from the *client* trying to make requests to the orthanc dicom-web endpoint and failing because of either CORS policy or a non-existent hostname. 
<img width="528" alt="image" src="https://user-images.githubusercontent.com/12169942/71039385-a66f4400-20e9-11ea-90de-a735bacda66d.png">

Is going directly to DICOMweb from the ohif viewer server still supported? Should I edit the nginx configuration in the container for CORS and just do dicomweb on the client side?

**Comment by dannyrb** [comment]
👋 Hello @cutecycle. I'm not sure I 100% follow. There are two ways to mitigate CORS issues:

1. Make sure the server that exposes the DICOMWeb endpoints has the appropriate [CORS Headers](https://auth0.com/blog/cors-tutorial-a-guide-to-cross-origin-resource-sharing/)

- `Access-Control-Allow-Origin`: The origin that is allowed to make the request, or * if a request can be made from any origin
- `Access-Control-Allow-Methods`: A comma-separated list of HTTP methods that are allowed
- `Access-Control-Allow-Headers`: A comma-separated list of the custom headers that are allowed to be sent
- `Access-Control-Max-Age`: The maximum duration that the response to the preflight request can be cached before another call is made

2. Host the client at the same domain/port as the DICOMWeb endpoints (no "cross origin" request, so everything just works)

----

You can see a few examples of our own usage of these. If anything seems incorrect, let me know. They may need cleaned up:

1. The default server the OHIF Viewer is configured to hit for test/development sets very permissive CORS headers
2. When using Orthanc as a PACS, it's not supposed to be exposed to open web traffic. One option is to use `nginx` to handle web requests, which provides a convenient place to set CORS headers. [We have an `nginx` configuration file lying around that should do that](https://github.com/OHIF/Viewers/blob/master/.docker/Nginx-Orthanc/config/nginx.conf)
3. In our [`nginx` + Image Archive](https://docs.ohif.org/deployment/recipes/nginx--image-archive.html) recipe, we show how to configure and deploy the web viewer _and_ `orthanc`. We host them at the same domain, so we don't need to set CORS headers. [The `nginx` config for that recipe is hiding here](https://github.com/OHIF/Viewers/blob/master/platform/viewer/.recipes/OpenResty-Orthanc/config/nginx.conf)

**Comment by cutecycle** [comment]
Hello, and Thank you. 

I've set the containers to host networking mode, and set all internal communication between OHIF and orthanc to 127.0.0.1:

```js
  servers: {
    dicomWeb: [
      {
        name: "orthanc",
        wadoUriRoot: "http://127.0.0.1:8042/wado",
        qidoRoot: "http://127.0.0.1:8042/dicom-web",
        wadoRoot: "http://127.0.0.1:8042/dicom-web",
        qidoSupportsIncludeField: false,
        imageRendering: "wadors",
        thumbnailRendering: "wadors",
        enableStudyLazyLoad: true,
      },
    ],
  },
```
```yaml
version: '3.6'
services:
  mongo:
    image: "mongo:latest"
    network_mode: host
    restart: always
  orthanc:
    image: jodogne/orthanc-plugins
    restart: always
    command: ["--trace","/etc/orthanc/orthanc.json" ]
    network_mode: host
    volumes:
       - ./configs/ohif-config/orthanc.json:/etc/orthanc/orthanc.json
  viewer:
    image: ohif/viewer:v2.2.0.5809
    restart: always
    network_mode: host
    ports:
      - "80:80"
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://127.0.0.1:27017/ohif
      - PUBLIC_URL=http://34.220.35.158/
    extra_hosts:
      - "pacsip:127.0.0.1"
      - "pacsIP:127.0.0.1"
    volumes:
      - ./configs/ohif-config/ohif.json:/app/app.json
      - ./configs/ohif-config/ohif.js:/usr/share/nginx/html/app-config.js
```

When you say "client on the same origin," do you mean the browser as well? I thought if I had both OHIF and orthanc on 127.0.0.1, the ohif/viewers container itself would GET `127.0.0.1:8042/dicom-web`, which should be allowed. 

But it looks like what's happening in newer versions is now the browser on an end-user machine is making an AJAX request to the configured DICOMweb endpoint URL, rather than the Viewers server.

Meteor/~0.4.0: OHIF backend makes the request on loopback

```
ESC[34mI20190826-18:46:46.732(0)? ESC[39m  dicomWeb: { endpoints: [ [Object] ] },
ESC[34mI20190826-18:46:46.732(0)? ESC[39m  dimse: { host: '127.0.0.1', hostAE: 'IMAGEMOVER_SCP', port: 11112 },
ESC[34mI20190826-18:46:46.732(0)? ESC[39m  public: {} }
ESC[34mI20190826-19:00:22.756(0)? ESC[39mhttp://127.0.0.1:8042/dicom-web/studies?limit=20&includefield=00081030%2C00080060
ESC[34mI20190826-19:00:22.764(0)? ESC[39mhttp://127.0.0.1:8042/dicom-web/studies?limit=20&includefield=00081030%2C00080060: 8ms
ESC[34mI20190826-19:35:59.354(0)? ESC[39mhttp://127.0.0.1:8042/dicom-web/studies?limit=20&includefield=00081030%2C00080060
```

React/v2+: OHIF frontend makes the request on XHR

![image](https://user-images.githubusercontent.com/12169942/71106832-97d66a80-2185-11ea-8fa8-98b6a24e1c5d.png)


Would you say it's best for me to add an nginx container that proxies to the orthanc container and overwrites the existing CORS headers?
