### ISSUE TITLE
Integration with Orthanc DicomWeb with HTTP Authorization 

### ISSUE THREAD

**Issue by FossilBlade** [OHIF/Viewers#1597]
**Description**

**Is there any documentation which describes the steps to use OHIF viewer with Orthanc DicomWeb which has HTTP authentication ?**

I have given it couple of tries but it work only for the first view where the patient list is shown and fails when clicking on a patient to view the images.  It asks for the orthanc password. **My guess is OHIF Viewer is not sending the Authorization Header in this ajax request. (Snapshot at the bottom)**

I am using docker-compose for latest orhtanc-plugins and ohif viewer 

My use case is to use the viewer to show the user dicom images, who doesnt any idea about the orthanc as the backend. Also i can't disable orhtanc's authentication as that would be a security issue.

Any help would be appreciated. 

**Also is there a way so that the dicomweb user and password can be hidden as it is clearly visible in the app-config.js file which gets down loaded. Basically a better way to protect the dicomweb credentials.** 

Here is my docker-compose
```
version: '3.6'
services:

  viewer:
    image: ohif/viewer:v3.8.16.10895
    container_name: viewer
    depends_on:
      - orthanc
    restart: always
    ports:
      - '80:80'
    networks:
      - frontend    
    volumes:
      # Nginx as a reversed proxy for orthanc and the viewer
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # OHIF Viewer configuration to reach DICOMWeb endpoints
      - ./config/viewer.js:/usr/share/nginx/html/app-config.js:ro

  orthanc:
    image: jodogne/orthanc-plugins:1.6.0
    container_name: orthanc    
    restart: always
    networks:
      - frontend     
    volumes:      
      - ./config/orthanc.json:/etc/orthanc/orthanc.json:ro      
    command: /etc/orthanc/orthanc.json

networks:
  frontend:
```

Here is the relevant orthanc config:
```
"AuthenticationEnabled" : true,
  "RegisteredUsers" : {
    "final1":"final1"
  },

  "DicomWeb" : {
    "Enable" : true,            // Whether DICOMweb support is enabled
    "Root" : "/dicom-web/",     // Root URI of the DICOMweb API (for QIDO-RS, STOW-RS and WADO-RS)
    "EnableWado" : true,        // Whether WADO-URI (previously known as WADO) support is enabled
    "WadoRoot" : "/wado",       // Root URI of the WADO-URI (aka. WADO) API
    "Ssl" : false,              // Whether HTTPS should be used for subsequent WADO-RS requests
    "QidoCaseSensitive" : true, // For QIDO-RS server, whether search is case sensitive (since release 0.5)
    "StudiesMetadata" : "Full", // How study-level metadata is retrieved (since release 1.1, cf. section below)
    "SeriesMetadata" : "Full"   // How series-level metadata is retrieved (since release 1.1, cf. section below)
  }
```

Here is the viewer.js dicom part

```
dicomWeb: [
        {
          name: 'ORTHANC',
          wadoUriRoot: 'http://localhost:80/pacs/wado',
          qidoRoot: 'http://localhost:80/pacs/dicom-web',
          wadoRoot: 'http://localhost:80/pacs/dicom-web',
          qidoSupportsIncludeField: true,
          imageRendering: 'wadors',
          thumbnailRendering: 'wadors',
          enableStudyLazyLoad: true,
	  	  requestOptions: {
		          auth: "demo:demo",
		          logRequests: true,
		          logResponses: false,
		          logTiming: true,
		          requestFromBrowser: true,
		        }
        },
      ],
```

Screenshot of send page:

![image](https://user-images.githubusercontent.com/32032862/78329439-34f6cb00-75de-11ea-8625-d736c032c12d.png)
