### ISSUE TITLE
PUBLIC_URL env variable does not seem to work using the published docker

### ISSUE THREAD

**Issue by HowardLander** [OHIF/Viewers#2225]
Hi all

We are attempting to use the published OHIF docker image in a system that requires the URL to be set at run time. We looked through the documents and found the PUBLIC_URL environment variable but it doesn't seem to be working as expected. For example we thought we could add something like

- PUBLIC_URL=/private/some-user-name/some-app-name/some-random-unique-id/

to our docker compose file and find the app at the URL but it doesn't seem to be working.  Any advice or ideas would be most appreciated.

Thanks
Howard Lander

**Comment by Diegovictorbr** [comment]
I think that it's the same problem I am facing. Here is the relevant Compose section:

```
ohif:
    image: ohif/viewer
    environment:
    - PUBLIC_URL=/ohif/
    ports:
      - 19861:80
    volumes:
      - ./ohif/app-config.js:/usr/share/nginx/html/app-config.js
      # - ./ohif/nginx.conf:/etc/nginx/nginx.conf:ro
```

But OHIF doesn't look for assets and scripts starting from /ohif/. However, routerBasename works as expected and i can serve the application at localhost:19861/ohif/
