### ISSUE TITLE
Backend connection for the OHIF viewer (docker) with Google HealthCare (JWT)

### ISSUE THREAD

**Issue by Bruno93160** [OHIF/Viewers#2388]
Hello everyone,

I am trying without success for the moment to be able to automatically connect the OHIF viewer (installed with docker) with my Google Healthcare Cloud.
On my site, I succeeded with the JWT and my Backend to connect to the Google Cloud: https://developers.google.com/identity/protocols/oauth2/service-account#httprest
But when I click on the Viewer link, the connection to the cloud does not work. I imagine that a configuration is missing on the Viewer docker so that it connects in JWT to the Cloud but I have not yet found how to do it.
Could you help me please? 

Thanks
Bruno

**Comment by Bruno92400** [comment]
More information about our stack : 

We have a main site with double authentication, that's why we don't need the user to log in a second time to access the Viewer with datas.
To retrieve file information and be able to upload Dicom on our main application we have successfully configured the Google Cloud connection with JWT for service account. 
We are therefore only missing the connection to the Google Cloud in the same way for the OHIF Viewer. 

**For localhost => docker-compose.yml :**
```
  dicom:
    image: ohif/viewer:v4.9.8.14493
    restart: on-failure
    environment:
      - "CLIENT_ID=xxx"
    volumes:
      - './apps/dicom/docker/app-config.js:/usr/share/nginx/html/app-config.js'
    ports:
      - '8065:80'
```

**app-config.js :**
```
window.config = {
  routerBasename: '/',
  showStudyList: true,
  /**
 * "White Labeling" is used to change the branding, look, and feel of the OHIF
 * Viewer. These settings, and the color variables that are used by our components,
 * are the easiest way to rebrand the application.
 *
 * More extensive changes are made possible through swapping out the UI library,
 * Viewer project, or extensions.
 */
  whiteLabeling: {
    /* Optional: Should return a React component to be rendered in the "Logo" section of the application's Top Navigation bar */
    createLogoComponentFn: function (React) {
      return React.createElement('a', {
        target: '_self',
        rel: 'noopener noreferrer',
        className: 'header-brand',
        href: '/',
        style: {
          display: 'block',
          textIndent: '-9999px',
          background: 'url(/svg-file-hosted-at-domain-root.svg)',
          backgroundSize: 'contain',
          backgroundRepeat: 'no-repeat',
          width: '200px',
        },
      });
    },
  },
  enableGoogleCloudAdapter: false,
  healthcareApiEndpoint: 'https://healthcare.googleapis.com/v1',
  servers: {
    // This is an array, but we'll only use the first entry for now
    dicomWeb: [],
  },
  // This is an array, but we'll only use the first entry for now
  oidc: [
    {
      // ~ REQUIRED
      // Authorization Server URL
      authority: 'https://accounts.google.com',
      client_id: 'xxx',
      redirect_uri: '/callback', // `OHIFStandaloneViewer.js`
      response_type: 'id_token token',
      scope:
        'email profile openid https://www.googleapis.com/auth/cloudplatformprojects.readonly https://www.googleapis.com/auth/cloud-healthcare',
      // ~ OPTIONAL
      post_logout_redirect_uri: '/logout-redirect.html',
      revoke_uri: 'https://accounts.google.com/o/oauth2/revoke?token=',
      automaticSilentRenew: true,
      revokeAccessTokenOnSignout: true,
    },
  ],
  studyListFunctionsEnabled: true,
};

```

**Comment by pavankjadda** [comment]
@Bruno92400 I have a similar requirement. We connect OHIF Viewer to GCP Health Care API. We do not want any authentication between OHIF viewer and Health Care API, since we already authenticate Web App that uses OHIF Viewer through another OIDC provider. I am having trouble to configure Service Account to do this. Few questions

**Dockerfile**
```
  dicom:
    image: ohif/viewer
    restart: on-failure
    environment:
      - "CLIENT_ID=xxx"
    volumes:
      - './apps/dicom/docker/app-config.js:/usr/share/nginx/html/app-config.js'
    ports:
      - '5001:80'
```

- I have service account at hand but don't know where to start. I looked at your **app-config.js** and don't see anywhere service account configuration. Where should I configure service account details in **app-config.js** ?
- If I were successful, When user views page `https://DOMAIN_NAME/viewer/ID` in OHIF viewer, would it automatically show the study without any issues?

Appreciate your response in advance
