### ISSUE TITLE
[Bug] OHIF Docker image does not seem to read app-config.js

### ISSUE THREAD

**Issue by nexmann** [OHIF/Viewers#3835]
### Describe the Bug

I am trying to set up a Orthanc + Ohif Viewer docker compose file such that I can locally use OHIF viewer on top of Orthanc's DICOMWeb server. But the OHIF viewer container does not seem to read my app-config.js.

### Steps to Reproduce

1. Set up docker-compose.yaml:

```
version: "3.9"
services:
  ohif:
    image: ohif/app:v3.5.0
    ports:
      - "3000:80"
    restart: always
    volumes:
      - ./ohif/ohif.js:/usr/share/nginx/html/app-config.js:ro
      - ./ohif/logo.png:/usr/share/nginx/html/logo.png:ro

  orthanc:
    image: jodogne/orthanc-plugins:1.12.1
    ports:
      - "8042:8042"
      - "4242:4242"
    restart: always
    volumes:
      - ./orthanc/orthanc.json:/etc/orthanc/orthanc.json:ro

```
     
2. Add ohif.js:
```
window.config = {
  routerBasename: '/',
  extensions: [],
  modes: [],
  showStudyList: true,
  dataSources: [
      {
          namespace: '@ohif/extension-default.dataSourcesModule.dicomweb',
          sourceName: 'dicomweb',
          configuration: {
            friendlyName: 'Orthanc DicomWeb Server',
            name: 'orthanc',
            wadoUriRoot: 'http://orthanc:8042/wado',
            qidoRoot: 'http://orthanc:8042/dicom-web',
            wadoRoot: 'http://orthanc:8042/dicom-web',
            qidoSupportsIncludeField: true,
            supportsReject: true,
            imageRendering: 'wadors',
            thumbnailRendering: 'wadors',
            enableStudyLazyLoad: true,
            supportsFuzzyMatching: true,
            supportsWildcard: true,
            omitQuotationForMultipartRequest: true,
          },
      },
  ],
  defaultDataSourceName: 'dicomweb',
};
```

3. Orthanc config has the following changed config fields:
`"AuthenticationEnabled" : false,
"RemoteAccessAllowed" : true,`

### The current behavior

The orthanc server seems correctly configured, and I can curl the DICOMweb server correctly. However, the OHIF container does not seem to respect the mounted app-config.js that I have provided. It just shows the standard studies no matter what I do. I even tried to insert syntax errors into the app-config.js, to force a crash, but it doesn't seem to read the file at all.

### The expected behavior

That the OHIF viewer connects to the DICOMweb backend as a data source.

### OS

Linux 18.04

### Node version

Docker version

### Browser

Chrome
