### ISSUE TITLE
Run docker image with default settings.

### ISSUE THREAD

**Issue by TZubiri** [OHIF/Viewers#392]
Considering the point of containerizing is to provide atomic, standard, self sufficient, out of the box, units of software. Would it make sense to package the docker distribution with a mongo database by default?

I ended up not using the docker container, since the local meteor installation provided sensible defaults.

**Comment by dannyrb** [comment]
Docker is not my area of expertise, so more than happy to discuss.

Each unit is atomic. It does one thing and is a self-sufficient building block, but those atomic elements work together to serve up an application?

Either way, I think the separate instances emulate a production setup. If I wanted to scale, I don't think I would want to scale the database and the web server at the same rate?

**Comment by TZubiri** [comment]
Docker, OHIF or MongoDB are not my area of expertise either.
The requirement to separate the database and web server for independent scaling makes sense.
Perhaps  the app could be packaged with a docker compose that sets up a mongodb container along with the current OHIF container? 

This way the technical components are containerized, but the docker swarm provides an atomic unit on the application level.

A nice bonus is that if someone needs to scale but doesn't know how,  it's possible to add a configuration option for scaling the database, and thus version control the scaling infrastructure.

**Comment by TZubiri** [comment]
I found an example of the setup I'm suggesting:

https://hub.docker.com/_/wordpress

This image provides a docker compose with 2 images, one for wordpress and another one for mysql:

```
version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
```
