### ISSUE TITLE
Orthanc keycloak fails due to webapp:latest not found on docker hub.[Bug] 

### ISSUE THREAD

**Issue by muzzkh** [OHIF/Viewers#4057]
### Describe the Bug

In the platform/app/.recipes/OpenResty-Orthanc-Keycloak  two main dockerfiles cannot be found on docker hub. I changed the keycloak from version 6.0.1 to version 9.0.2 being pulled from quay.io. This fixed keycloak. However, webapp:latest produces the following error

`! ohif_viewer Warning      pull access denied for webapp, repository does not exist or may require 'docker login': denied: requested access to the resource is denied  `
Upon further inspection the image does not appear to exist on dockerhub and I do not know where it is pulled from.

### Steps to Reproduce

1. Replace the old keycloak image with the following
```
keycloak:
    image: quay.io/keycloak/keycloak:9.0.2
    hostname: keycloak
    container_name: keycloak
    volumes:
      - ./volumes/keycloak-themes/ohif:/opt/jboss/keycloak/themes/ohif
      - ./config/ohif-keycloak-realm.json:/tmp/ohif-keycloak-realm.json
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_SCHEMA: public
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_IMPORT: /tmp/ohif-keycloak-realm.json
      PROXY_ADDRESS_FORWARDING: 'true'
    depends_on:
      - postgres
    restart: unless-stopped
```

2. Then follow platform/app/.recipes/OpenResty-Orthanc-Keycloak  and run docker compose up

### The current behavior

Current behavior will deny access to pull webapp but will compile given the above keycloak image and will successfully load keycloak components. However, upon visition 127.0.0.1/ the page will not be found and simply appear blank.

### The expected behavior

Expected behavior is a login screen for keycloak.

### OS

Mac Sonoma

### Node version

v21.6.1

### Browser

Chrome/Edge
