### ISSUE TITLE
[Bug] error when creating a report

### ISSUE THREAD

**Issue by insinfo** [OHIF/Viewers#4139]
### Describe the Bug

error when creating a report

![image](https://github.com/OHIF/Viewers/assets/12227024/df0a94f1-c134-4277-b517-df710bbe6c89)

```xml
<?xml version="1.0" encoding="UTF-8"?><NativeDicomModel xml:space="preserve"><DicomAttribute keyword="ErrorComment" tag="00000902" vr="LO"><Value number="1">javax.ejb.EJBTransactionRolledbackException: Transaction rolled back</Value></DicomAttribute><DicomAttribute keyword="RetrieveURL" tag="00081190" vr="UR"/><DicomAttribute keyword="FailedSOPSequence" tag="00081198" vr="SQ"><Item number="1"><DicomAttribute keyword="ReferencedSOPClassUID" tag="00081150" vr="UI"><Value number="1">1.2.840.10008.5.1.4.1.1.88.22</Value></DicomAttribute><DicomAttribute keyword="ReferencedSOPInstanceUID" tag="00081155" vr="UI"><Value number="1">2.25.689745914154889666936540964949817258292</Value></DicomAttribute><DicomAttribute keyword="FailureReason" tag="00081197" vr="US"><Value number="1">272</Value></DicomAttribute></Item></DicomAttribute></NativeDicomModel>
```

![image](https://github.com/OHIF/Viewers/assets/12227024/b7b1a3bc-5686-4829-9147-564d69cd900e)

## docker-compose.yml
```yml
version: "3.8"
networks:
  dcm4chee_default:
    #driver: overlay

volumes:
    storage-storage:
      driver: local
      driver_opts:
        type: cifs
        device: //10.0.0.30/Imagens/dcm4chee-arc/wildfly/data/fs1
        o: addr=10.0.0.30,username=pacs,password=P@csPMR0,file_mode=0600,dir_mode=0700,uid=1023,gid=1023,vers=2.0
    storage-wildfly:
      driver: local
      driver_opts:
        type: none
        o: bind        
        device: ${PACS_PATH}/wildfly          
    storage-db:
      driver: local
      driver_opts:
        type: none
        o: bind        
        device: ${PACS_PATH}/db       
    storage-ldap:     
      driver: local
      driver_opts:
        type: none
        o: bind        
        device: ${PACS_PATH}/ldap    
    storage-slapd:     
      driver: local
      driver_opts:
        type: none
        o: bind        
        device: ${PACS_PATH}/slapd.d   
    storage-oviyam:     
      driver: local
      driver_opts:
        type: none
        o: bind        
        device: ${PACS_PATH}/oviyam    

    storage-dbkeycloak:     
      driver: local
      driver_opts:
        type: none
        o: bind        
        device: ${PACS_PATH}/dbkeycloak    
      
services:
  ldap:
    image: dcm4che/slapd-dcm4chee:2.4.44-12.0
    ports: 
      - "389:389" 
    #restart: always
    networks:
      - dcm4chee_default
    volumes:
      - ${ETC_PATH}/localtime:/etc/localtime:ro
      - ${ETC_PATH}/timezone:/etc/timezone:ro
      - storage-ldap:/var/lib/ldap 
      - storage-slapd:/etc/ldap/slapd.d 
  db:
    image: dcm4che/postgres-dcm4chee:10.0-12
    ports:
      - "5432:5432" 
    #restart: always
    networks:
      - dcm4chee_default
    volumes:
      - ${ETC_PATH}/localtime:/etc/localtime:ro 
      - ${ETC_PATH}/timezone:/etc/timezone:ro 
      - storage-db:/var/lib/postgresql/data 
    environment:
      POSTGRES_DB: pacsdb 
      POSTGRES_USER: pacs 
      POSTGRES_PASSWORD: pacs
  arc:
    image: dcm4che/dcm4chee-arc-psql:5.12.0
    ports: 
      - "8080:8080"
      - "8443:8443"
      - "9990:9990"
      - "11112:11112"
      - "2575:2575"
    #restart: always
    networks:
      - dcm4chee_default   
    environment:
      POSTGRES_DB: pacsdb 
      POSTGRES_USER: pacs 
      POSTGRES_PASSWORD: pacs
      WILDFLY_WAIT_FOR: ldap:389 db:5432      
    volumes:
      - ${ETC_PATH}/localtime:/etc/localtime:ro 
      - ${ETC_PATH}/timezone:/etc/timezone:ro 
      - storage-wildfly:/opt/wildfly/standalone
      - storage-storage:/opt/wildfly/standalone/data/fs1      
    depends_on:
      - ldap
      - db  
  oviyam:
    image: informaticamedica/oviyam:2.7.1
    ports: ["83:8080","1025:1025"]
    #restart: always
    networks:
      - dcm4chee_default
    volumes:
      - storage-oviyam:/usr/local/tomcat/work
      - ${PACS_PATH}/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
    depends_on:
      - arc  
  
  dbkeycloak:
    image: postgres
    #restart: unless-stopped
    volumes:
        - storage-dbkeycloak:/var/lib/postgresql/data
    environment: 
        POSTGRES_DB: keycloak
        POSTGRES_USER: pacs
        POSTGRES_PASSWORD: pacs
    logging:
      options:
        max-size: 10m
        max-file: "13"    
    ports:
        - 5433:5432
    networks: 
        - dcm4chee_default
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4     
    #,"--http-relative-path=auth"
    #,"--hostname-strict=false"
    command: ["start-dev","--proxy-headers", "xforwarded"]
    restart: unless-stopped
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: pacs
      KC_DB_PASSWORD: pacs
      KC_DB_URL_PORT: 5433
      KC_DB_URL: jdbc:postgresql://10.0.0.29:5433/keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd   
      KC_HTTP_ENABLED: true
      #KC_HOSTNAME: keycloak
      #KC_HOSTNAME_URL: http://localhost:3333/auth
      #KC_HOSTNAME_ADMIN_URL: http://localhost:3333/auth
      KC_HTTP_RELATIVE_PATH: /auth
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HOSTNAME_STRICT: false
      #KC_PROXY: edge
      #KC_PROXY_ADDRESS_FORWARDING: true     
    ports:
        - 3333:8080
    depends_on:
        - dbkeycloak
    networks:
        - dcm4chee_default    
  openresty:
    build:
      context: ./openresty
      dockerfile: Dockerfile
    image: openresty
    ports:
      - 80:80   
      - 443:443
    networks:
      - dcm4chee_default
    volumes:  
      - ${PACS_PATH}/openresty/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro          
      - ${PACS_PATH}/openresty/server.conf:/etc/nginx/conf.d/default.conf
      - ${PACS_PATH}/openresty/logs:/var/logs/nginx
      - ${PACS_PATH}/openresty/ssl/riodasostras_rj_gov_br_chained.crt:/etc/nginx/ssl/nginx.crt
      - ${PACS_PATH}/openresty/ssl/riodasostras_rj_gov_br.key:/etc/nginx/ssl/nginx.key
    
  ohif:   
    image: ohif/app:v3.9.0-beta.7
    volumes:
      - ${PACS_PATH}/ohif/app-config.js:/usr/share/nginx/html/app-config.js
    ports:      
      - 3000:80
    networks:
      - dcm4chee_default  
    depends_on:     
      - openresty        
```

### The current behavior

does not save the report or export the report

### The expected behavior

save the report and be able to export the report

### OS

Windows 11

### Node version

OHIF default image

### Browser

Chrome last version in windows
