### ISSUE TITLE
Orthanc docker-compose file missing

### ISSUE THREAD

**Issue by timoangerer** [OHIF/Viewers#785]
It seems like the docker-compose file for the local Orthanc server setup is missing in the latest version of the viewer.

Could someone give me an updated Step-by-step guide on how to run the server locally and connect it to the ohif viewer? Or alternatively how I can load local Dicom files directly into the viewer without a server in between.

**Comment by dannyrb** [comment]
@timoangerer, we _just_ switched to a monorepo, so a lot of files have been shifted to new places. Are there any docs/commands in particular that seem off or missing? Helping us identify stuff like this will allow us (or other contributors) to better prioritize fixes.

I recommend checking out the `platform/viewer/*` location for most files that used to exist at the top level of this repository.

**Comment by timoangerer** [comment]
I looked at this page of the docs: https://docs.ohif.org/essentials/data-source.html

I tried to run the command `yarn run orthanc:up` as written in the docs, but it returns an error:
`ERROR: .FileNotFoundError: [Errno 2] No such file or directory: './docker/Nginx-Orthanc/docker-compose.yml'`

It seems the docker folder does not exist anymore.

**Comment by dannyrb** [comment]
It looks like that path now lives at `/platform/viewer/.recipes/*`

The scripts probably just need to be updated to use the correct path. There could be one or two other path related issues that need resolved, but all the necessary parts should be there.

**Comment by mtm12** [comment]
The monorepo simplies the setup significantly. To connect to a remote instance of Orthanc, set the wadoUriRoot, qidoRoot, and wadoRoot in \platform\viewer\public\config\default.js to point to the remote server and run yarn run dev.

**Comment by MathisGuilhin** [comment]
@timoangerer have you figured out something? 

I fixed the first error by modifying the dockerfile location (that now works)
Now docker-compose up fails at step 6/24 : 
```shell
Service 'ohif_viewer' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder773718913/package.json: no such file or directory
```

Do you have any clues?

Thanks

**Comment by MathisGuilhin** [comment]
I figured it out.
If the whole docker process build, I could submit a PR for the changes

**Comment by timoangerer** [comment]
I've figured it out. I added an nginx service to the docker-compose file. Now there are also no errors with CORS.

This is the docker-compose:
```
version: '3.5'

services:
  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443

  orthanc:
    image: jodogne/orthanc-plugins
    hostname: orthanc
    volumes:
      # Config
      - ./config/orthanc.json:/etc/orthanc/orthanc.json:ro
      # Persist data
      - ./volumes/orthanc-db/:/var/lib/orthanc/db/
    ports:
      - '4242:4242' # DICOM
      - '8042:8042' # Web
    restart: unless-stopped

```

You might need to change the nginx port from 80:80 to something like 8888:80 if that port is already used.
